name: CI

on:
  pull_request:
    paths:
      - '**'
      - '!benchmark/**'
      - '!framer/**'
      - '!modules/**'
      - '!netlify/**'
      - '!packages/**'
      - '!scripts/**'
      - '!test/**'

permissions: {}

jobs:
  test-dev:
    if: ${{ github.actor != 'l10nbot' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - run: 'echo "No build required"'
